# Generated by Django 2.1.2 on 2019-02-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Nama barang')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi barang')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Foto barang')),
                ('urlVideo', models.URLField(blank=True, null=True, verbose_name='Link Video')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification input: Name: specification')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('Jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Category')),
            ],
        ),
    ]
