# Generated by Django 2.1.7 on 2019-02-25 06:29

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.AddField(
            model_name='item',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 1'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 10'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 2'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 3'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 4'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 5'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 6'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 7'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 8'),
        ),
        migrations.AddField(
            model_name='item',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang 9'),
        ),
    ]
