# Generated by Django 2.1.7 on 2019-03-07 08:37

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190225_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.name_upload, verbose_name='Foto barang Utama'),
        ),
        migrations.AlterField(
            model_name='item',
            name='specification',
            field=models.TextField(blank=True, null=True, verbose_name='Specification input: (Input) Name: specification'),
        ),
    ]
