# Generated by Django 2.1.7 on 2019-03-07 15:03

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190307_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture1',
            field=models.ImageField(blank=True, default='media/local/1.png', upload_to=item.models.name_upload, verbose_name='Foto barang Utama'),
        ),
    ]
