# Generated by Django 2.1.7 on 2019-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20190307_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorite',
            field=models.BooleanField(blank=True, default=False, verbose_name='Favorite'),
        ),
    ]
