# Generated by Django 2.1.7 on 2019-03-16 17:01

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture1',
            field=models.ImageField(upload_to=item.models.name_upload, verbose_name='Foto barang Utama'),
        ),
    ]
