# Generated by Django 2.1.7 on 2019-04-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20190331_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
