# Generated by Django 2.1.2 on 2019-04-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20190403_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
    ]
