# Generated by Django 2.2 on 2019-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20190412_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='urlVideo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link Video'),
        ),
    ]
