# Generated by Django 2.2 on 2019-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20190416_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='urlVideo',
            field=models.URLField(blank=True, null=True, verbose_name='Link Video'),
        ),
    ]
