# Generated by Django 2.1.15 on 2026-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20190416_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('InStock', 'Tersedia / siap kirim'), ('PreOrder', 'Pre-order'), ('OutOfStock', 'Stok habis'), ('Discontinued', 'Tidak diproduksi lagi')], default='InStock', max_length=20, verbose_name='Ketersediaan'),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, default='Lexia', max_length=80, verbose_name='Merek'),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Ringkasan di hasil pencarian Google. Kosongkan untuk memakai ringkasan otomatis. Ideal 150-160 karakter.', max_length=180, verbose_name='Meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Judul di Google & saat link dibagikan. Kosongkan untuk memakai nama halaman. Ideal 50-60 karakter.', max_length=70, verbose_name='Meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='item',
            name='model_code',
            field=models.CharField(blank=True, help_text='mis. 4606Z, 50R. Dipakai sebagai SKU/MPN pada data terstruktur.', max_length=60, verbose_name='Kode / tipe model'),
        ),
        migrations.AddField(
            model_name='item',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Centang agar halaman ini tidak muncul di hasil pencarian.', verbose_name='Sembunyikan dari Google (noindex)'),
        ),
        migrations.AddField(
            model_name='item',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Tampil saat link dibagikan di WhatsApp/Facebook. Ukuran ideal 1200x630 px. Kosongkan untuk memakai foto utama.', null=True, upload_to='seo/', verbose_name='Gambar share (OG image)'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Kosongkan bila harga hanya lewat penawaran.', max_digits=12, null=True, verbose_name='Harga (Rp)'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_on_request',
            field=models.BooleanField(default=True, verbose_name='Harga hubungi kami'),
        ),
        migrations.AddField(
            model_name='item',
            name='summary',
            field=models.CharField(blank=True, help_text='1-2 kalimat untuk kartu produk & meta description. Kosongkan untuk memakai potongan deskripsi otomatis.', max_length=300, verbose_name='Ringkasan singkat'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Terakhir diperbarui'),
        ),
    ]
