# Generated by Django 2.1.15 on 2026-09-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20260907_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nama barang'),
        ),
    ]
