# Generated by Django 2.1.15 on 2026-09-07 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20260907_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='feature_rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 = kartu besar (hero), 2-5 = kartu standar di bagian "Produk unggulan". Kosongkan bila tidak ditampilkan di beranda.', null=True, verbose_name='Urutan unggulan di beranda'),
        ),
        migrations.AddField(
            model_name='item',
            name='replacement',
            field=models.ForeignKey(blank=True, help_text='Dipakai bila ketersediaan = "Tidak diproduksi lagi". Halaman produk ini akan menampilkan tautan ke produk pengganti.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='item.Item', verbose_name='Produk pengganti'),
        ),
    ]
