# Generated by Django 2.1.15 on 2026-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20260907_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi barang'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi barang'),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='Ringkasan di hasil pencarian Google. Kosongkan untuk memakai ringkasan otomatis. Ideal 150-160 karakter.', max_length=180, null=True, verbose_name='Meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_description_ind',
            field=models.CharField(blank=True, help_text='Ringkasan di hasil pencarian Google. Kosongkan untuk memakai ringkasan otomatis. Ideal 150-160 karakter.', max_length=180, null=True, verbose_name='Meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Judul di Google & saat link dibagikan. Kosongkan untuk memakai nama halaman. Ideal 50-60 karakter.', max_length=70, null=True, verbose_name='Meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_title_ind',
            field=models.CharField(blank=True, help_text='Judul di Google & saat link dibagikan. Kosongkan untuk memakai nama halaman. Ideal 50-60 karakter.', max_length=70, null=True, verbose_name='Meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Nama barang'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Nama barang'),
        ),
        migrations.AddField(
            model_name='item',
            name='specification_en',
            field=models.TextField(blank=True, null=True, verbose_name='Specification input: (Input) Name: specification'),
        ),
        migrations.AddField(
            model_name='item',
            name='specification_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Specification input: (Input) Name: specification'),
        ),
        migrations.AddField(
            model_name='item',
            name='summary_en',
            field=models.CharField(blank=True, help_text='1-2 kalimat untuk kartu produk & meta description. Kosongkan untuk memakai potongan deskripsi otomatis.', max_length=300, null=True, verbose_name='Ringkasan singkat'),
        ),
        migrations.AddField(
            model_name='item',
            name='summary_ind',
            field=models.CharField(blank=True, help_text='1-2 kalimat untuk kartu produk & meta description. Kosongkan untuk memakai potongan deskripsi otomatis.', max_length=300, null=True, verbose_name='Ringkasan singkat'),
        ),
    ]
