# Generated by Django 2.1.2 on 2019-04-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20190331_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['jenis'], 'verbose_name_plural': 'Categories'},
        ),
    ]
