# Generated by Django 2.1.15 on 2026-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20190412_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='intro',
            field=models.TextField(blank=True, help_text='1-2 paragraf yang tampil di atas daftar produk. Konten unik di sini sangat membantu peringkat kategori ini di Google.', verbose_name='Teks pengantar kategori'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Ringkasan di hasil pencarian Google. Kosongkan untuk memakai ringkasan otomatis. Ideal 150-160 karakter.', max_length=180, verbose_name='Meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Judul di Google & saat link dibagikan. Kosongkan untuk memakai nama halaman. Ideal 50-60 karakter.', max_length=70, verbose_name='Meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Centang agar halaman ini tidak muncul di hasil pencarian.', verbose_name='Sembunyikan dari Google (noindex)'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Tampil saat link dibagikan di WhatsApp/Facebook. Ukuran ideal 1200x630 px. Kosongkan untuk memakai foto utama.', null=True, upload_to='seo/', verbose_name='Gambar share (OG image)'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Terakhir diperbarui'),
        ),
    ]
