# Generated by Django 2.1.15 on 2026-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20260907_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='intro_en',
            field=models.TextField(blank=True, help_text='1-2 paragraf yang tampil di atas daftar produk. Konten unik di sini sangat membantu peringkat kategori ini di Google.', null=True, verbose_name='Teks pengantar kategori'),
        ),
        migrations.AddField(
            model_name='category',
            name='intro_ind',
            field=models.TextField(blank=True, help_text='1-2 paragraf yang tampil di atas daftar produk. Konten unik di sini sangat membantu peringkat kategori ini di Google.', null=True, verbose_name='Teks pengantar kategori'),
        ),
        migrations.AddField(
            model_name='category',
            name='jenis_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Jenis'),
        ),
        migrations.AddField(
            model_name='category',
            name='jenis_ind',
            field=models.CharField(max_length=300, null=True, verbose_name='Jenis'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='Ringkasan di hasil pencarian Google. Kosongkan untuk memakai ringkasan otomatis. Ideal 150-160 karakter.', max_length=180, null=True, verbose_name='Meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ind',
            field=models.CharField(blank=True, help_text='Ringkasan di hasil pencarian Google. Kosongkan untuk memakai ringkasan otomatis. Ideal 150-160 karakter.', max_length=180, null=True, verbose_name='Meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Judul di Google & saat link dibagikan. Kosongkan untuk memakai nama halaman. Ideal 50-60 karakter.', max_length=70, null=True, verbose_name='Meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_ind',
            field=models.CharField(blank=True, help_text='Judul di Google & saat link dibagikan. Kosongkan untuk memakai nama halaman. Ideal 50-60 karakter.', max_length=70, null=True, verbose_name='Meta title (SEO)'),
        ),
    ]
