# Generated by Django 2.1.15 on 2026-09-06 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0006_auto_20260907_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Judul di Google & saat link dibagikan. Kosongkan untuk memakai nama halaman. Ideal 50-60 karakter.', max_length=70, verbose_name='Meta title (SEO)')),
                ('meta_description', models.CharField(blank=True, help_text='Ringkasan di hasil pencarian Google. Kosongkan untuk memakai ringkasan otomatis. Ideal 150-160 karakter.', max_length=180, verbose_name='Meta description (SEO)')),
                ('og_image', models.ImageField(blank=True, help_text='Tampil saat link dibagikan di WhatsApp/Facebook. Ukuran ideal 1200x630 px. Kosongkan untuk memakai foto utama.', null=True, upload_to='seo/', verbose_name='Gambar share (OG image)')),
                ('noindex', models.BooleanField(default=False, help_text='Centang agar halaman ini tidak muncul di hasil pencarian.', verbose_name='Sembunyikan dari Google (noindex)')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Terakhir diperbarui')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug URL')),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('published', 'Terbit')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, help_text='Diisi otomatis saat status diubah ke Terbit bila masih kosong.', null=True, verbose_name='Tanggal terbit')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Gambar sampul')),
                ('excerpt', models.CharField(blank=True, help_text='Tampil di daftar artikel & sebagai meta description bila kosong.', max_length=300, verbose_name='Ringkasan')),
                ('body', models.TextField(help_text='Boleh berisi HTML (h2, h3, p, ul, a, img, blockquote, ...).', verbose_name='Isi artikel')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('related_category', models.ForeignKey(blank=True, help_text='Menautkan artikel ke satu kategori mesin (untuk internal link).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='page.Category', verbose_name='Kategori produk terkait')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-published_at', '-created'],
            },
        ),
    ]
