# Generated by Django 2.1.15 on 2026-09-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('panduan', 'Panduan Membeli'), ('perbandingan', 'Perbandingan'), ('perawatan', 'Perawatan'), ('tips', 'Tips & Wawasan'), ('berita', 'Berita')], default='tips', help_text='Label editorial yang tampil di kartu artikel (mis. "Panduan Membeli").', max_length=20, verbose_name='Tag artikel'),
        ),
    ]
