# Generated by Django 2.1.15 on 2026-09-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Kosongkan untuk memakai tombol otomatis dari kategori terkait.', max_length=80, verbose_name='Teks tombol akhir artikel'),
        ),
        migrations.AddField(
            model_name='post',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Path internal (mis. /katalog/) atau URL lengkap (https://...).', max_length=300, verbose_name='Tautan tombol akhir artikel'),
        ),
    ]
