# Generated by Django 2.1.15 on 2026-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20260907_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(help_text='Boleh berisi HTML (h2, h3, p, ul, a, img, blockquote, ...).', null=True, verbose_name='Isi artikel'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ind',
            field=models.TextField(help_text='Boleh berisi HTML (h2, h3, p, ul, a, img, blockquote, ...).', null=True, verbose_name='Isi artikel'),
        ),
        migrations.AddField(
            model_name='post',
            name='cta_label_en',
            field=models.CharField(blank=True, help_text='Kosongkan untuk memakai tombol otomatis dari kategori terkait.', max_length=80, null=True, verbose_name='Teks tombol akhir artikel'),
        ),
        migrations.AddField(
            model_name='post',
            name='cta_label_ind',
            field=models.CharField(blank=True, help_text='Kosongkan untuk memakai tombol otomatis dari kategori terkait.', max_length=80, null=True, verbose_name='Teks tombol akhir artikel'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.CharField(blank=True, help_text='Tampil di daftar artikel & sebagai meta description bila kosong.', max_length=300, null=True, verbose_name='Ringkasan'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_ind',
            field=models.CharField(blank=True, help_text='Tampil di daftar artikel & sebagai meta description bila kosong.', max_length=300, null=True, verbose_name='Ringkasan'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='Ringkasan di hasil pencarian Google. Kosongkan untuk memakai ringkasan otomatis. Ideal 150-160 karakter.', max_length=180, null=True, verbose_name='Meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_ind',
            field=models.CharField(blank=True, help_text='Ringkasan di hasil pencarian Google. Kosongkan untuk memakai ringkasan otomatis. Ideal 150-160 karakter.', max_length=180, null=True, verbose_name='Meta description (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Judul di Google & saat link dibagikan. Kosongkan untuk memakai nama halaman. Ideal 50-60 karakter.', max_length=70, null=True, verbose_name='Meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_ind',
            field=models.CharField(blank=True, help_text='Judul di Google & saat link dibagikan. Kosongkan untuk memakai nama halaman. Ideal 50-60 karakter.', max_length=70, null=True, verbose_name='Meta title (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Judul'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ind',
            field=models.CharField(max_length=200, null=True, verbose_name='Judul'),
        ),
    ]
