# Generated by Django 2.1.7 on 2019-04-03 12:34

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=homepage.models.name_upload, verbose_name='Foto brosur')),
            ],
        ),
    ]
