# Generated by Django 2.1.15 on 2026-09-06 18:05

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brochure',
            options={'ordering': ['order', '-updated'], 'verbose_name': 'Brosur', 'verbose_name_plural': 'Brosur'},
        ),
        migrations.AddField(
            model_name='brochure',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Deskripsi singkat'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='file',
            field=models.FileField(blank=True, help_text='Opsional. Berkas PDF yang bisa diunduh pengunjung.', null=True, upload_to=homepage.models.file_upload, verbose_name='Berkas (PDF)'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Tampilkan'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='title',
            field=models.CharField(default='Brosur', max_length=200, verbose_name='Judul brosur'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='picture',
            field=models.ImageField(upload_to=homepage.models.name_upload, verbose_name='Gambar sampul'),
        ),
    ]
