# Generated by Django 2.1.15 on 2026-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20260907_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Deskripsi singkat'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='description_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Deskripsi singkat'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='title_en',
            field=models.CharField(default='Brosur', max_length=200, null=True, verbose_name='Judul brosur'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='title_ind',
            field=models.CharField(default='Brosur', max_length=200, null=True, verbose_name='Judul brosur'),
        ),
    ]
