# Generated by Django 2.1.15 on 2026-09-07 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0006_auto_20260907_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama lengkap')),
                ('whatsapp', models.CharField(max_length=32, verbose_name='No. WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('status', models.CharField(choices=[('new', 'Baru'), ('read', 'Dibaca'), ('in_progress', 'Ditindaklanjuti'), ('done', 'Selesai'), ('archived', 'Arsip')], default='new', max_length=16, verbose_name='Status')),
                ('handled_note', models.TextField(blank=True, help_text='Catatan tim — tidak tampil ke pengunjung.', verbose_name='Catatan internal')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Masuk pada')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='page.Category', verbose_name='Mesin yang diminati')),
            ],
            options={
                'verbose_name': 'Pesan Masuk',
                'verbose_name_plural': 'Pesan Masuk (Hubungi Kami)',
                'ordering': ['-created'],
            },
        ),
    ]
