# Generated by Django 2.1.15 on 2026-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Lexia Machinery', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Distributor mesin percetakan & finishing', max_length=200)),
                ('default_meta_description', models.CharField(blank=True, help_text='Dipakai pada halaman yang tidak punya meta description sendiri.', max_length=200)),
                ('default_og_image', models.ImageField(blank=True, help_text='Gambar share default (1200x630).', null=True, upload_to='seo/')),
                ('phone_primary', models.CharField(blank=True, default='(+62) 61 4154876', max_length=40)),
                ('phone_secondary', models.CharField(blank=True, default='(+62) 61 4515028', max_length=40)),
                ('whatsapp_number', models.CharField(blank=True, default='6285275103333', help_text='Format internasional tanpa tanda +, mis. 6285275103333.', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, default='Jalan Mesjid No. 165', max_length=255)),
                ('city', models.CharField(blank=True, default='Medan', max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('region', models.CharField(blank=True, default='Sumatera Utara', max_length=80)),
                ('country', models.CharField(blank=True, default='ID', max_length=2)),
                ('latitude', models.CharField(blank=True, max_length=32)),
                ('longitude', models.CharField(blank=True, max_length=32)),
                ('opening_hours', models.CharField(blank=True, default='Mo-Sa 08:00-17:00', help_text="Format schema.org, mis. 'Mo-Sa 08:00-17:00'.", max_length=120)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/lexiamachinery.ind/')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/lexiamachinery.ind')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/user/JeffryAldiP')),
                ('tokopedia_url', models.URLField(blank=True, default='https://www.tokopedia.com/lexiamachinery')),
                ('google_site_verification', models.CharField(blank=True, help_text='Isi content dari tag verifikasi Google Search Console.', max_length=120)),
                ('bing_site_verification', models.CharField(blank=True, max_length=120)),
                ('ga_measurement_id', models.CharField(blank=True, help_text='ID Google Analytics 4, mis. G-XXXXXXXXXX.', max_length=40)),
            ],
            options={
                'verbose_name': 'Pengaturan Situs & SEO',
                'verbose_name_plural': 'Pengaturan Situs & SEO',
            },
        ),
    ]
