# Generated by Django 2.1.15 on 2026-09-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_body',
            field=models.TextField(blank=True, default='Lexia Machinery, di bawah Pelita Graphic Supplies, menyediakan mesin potong kertas, laminating, jilid lem, dan mesin finishing lainnya untuk pelaku usaha percetakan dan photocopy di seluruh Indonesia.\n\nKini kami berkembang melayani Medan, Jakarta, dan seluruh Indonesia — dengan konsultasi langsung, dukungan purna jual, dan pengiriman ke seluruh penjuru negeri.', help_text='Satu baris kosong = paragraf baru.', verbose_name='Isi halaman Tentang'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_headline',
            field=models.CharField(blank=True, default='Distributor mesin percetakan tepercaya, sejak awal berdiri di Medan', max_length=200, verbose_name='Judul halaman Tentang'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Showroom / gudang. Rasio 4:3, mis. 1200x900.', null=True, upload_to='seo/', verbose_name='Foto halaman Tentang'),
        ),
    ]
