# Generated by Django 2.1.15 on 2026-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20260907_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_body_en',
            field=models.TextField(blank=True, default='Lexia Machinery, di bawah Pelita Graphic Supplies, menyediakan mesin potong kertas, laminating, jilid lem, dan mesin finishing lainnya untuk pelaku usaha percetakan dan photocopy di seluruh Indonesia.\n\nKini kami berkembang melayani Medan, Jakarta, dan seluruh Indonesia — dengan konsultasi langsung, dukungan purna jual, dan pengiriman ke seluruh penjuru negeri.', help_text='Satu baris kosong = paragraf baru.', null=True, verbose_name='Tentang: isi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_body_ind',
            field=models.TextField(blank=True, default='Lexia Machinery, di bawah Pelita Graphic Supplies, menyediakan mesin potong kertas, laminating, jilid lem, dan mesin finishing lainnya untuk pelaku usaha percetakan dan photocopy di seluruh Indonesia.\n\nKini kami berkembang melayani Medan, Jakarta, dan seluruh Indonesia — dengan konsultasi langsung, dukungan purna jual, dan pengiriman ke seluruh penjuru negeri.', help_text='Satu baris kosong = paragraf baru.', null=True, verbose_name='Tentang: isi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_headline_en',
            field=models.CharField(blank=True, default='Distributor mesin percetakan tepercaya, sejak awal berdiri di Medan', max_length=200, null=True, verbose_name='Tentang: judul (H1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_headline_ind',
            field=models.CharField(blank=True, default='Distributor mesin percetakan tepercaya, sejak awal berdiri di Medan', max_length=200, null=True, verbose_name='Tentang: judul (H1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_intro',
            field=models.TextField(blank=True, default='Konsultasi kebutuhan mesin percetakan Anda, atau kunjungi langsung showroom kami di Medan.', verbose_name='Hubungi Kami: paragraf pembuka'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_intro_en',
            field=models.TextField(blank=True, default='Konsultasi kebutuhan mesin percetakan Anda, atau kunjungi langsung showroom kami di Medan.', null=True, verbose_name='Hubungi Kami: paragraf pembuka'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_intro_ind',
            field=models.TextField(blank=True, default='Konsultasi kebutuhan mesin percetakan Anda, atau kunjungi langsung showroom kami di Medan.', null=True, verbose_name='Hubungi Kami: paragraf pembuka'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description_en',
            field=models.CharField(blank=True, help_text='Dipakai pada halaman yang tidak punya meta description sendiri.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description_ind',
            field=models.CharField(blank=True, help_text='Dipakai pada halaman yang tidak punya meta description sendiri.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_headline',
            field=models.CharField(blank=True, default='Mesin percetakan yang bekerja sekeras bisnis Anda', max_length=200, verbose_name='Beranda: judul utama (H1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_headline_en',
            field=models.CharField(blank=True, default='Mesin percetakan yang bekerja sekeras bisnis Anda', max_length=200, null=True, verbose_name='Beranda: judul utama (H1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_headline_ind',
            field=models.CharField(blank=True, default='Mesin percetakan yang bekerja sekeras bisnis Anda', max_length=200, null=True, verbose_name='Beranda: judul utama (H1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_kicker',
            field=models.CharField(blank=True, default='Distributor Resmi — Medan · Jakarta · Seluruh Indonesia', max_length=160, verbose_name='Beranda: kicker'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_kicker_en',
            field=models.CharField(blank=True, default='Distributor Resmi — Medan · Jakarta · Seluruh Indonesia', max_length=160, null=True, verbose_name='Beranda: kicker'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_kicker_ind',
            field=models.CharField(blank=True, default='Distributor Resmi — Medan · Jakarta · Seluruh Indonesia', max_length=160, null=True, verbose_name='Beranda: kicker'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_lead',
            field=models.TextField(blank=True, default='Potong, laminating, jilid, dan finishing — satu distributor tepercaya untuk seluruh kebutuhan mesin percetakan dan photocopy Anda.', verbose_name='Beranda: paragraf pembuka'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_lead_en',
            field=models.TextField(blank=True, default='Potong, laminating, jilid, dan finishing — satu distributor tepercaya untuk seluruh kebutuhan mesin percetakan dan photocopy Anda.', null=True, verbose_name='Beranda: paragraf pembuka'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_lead_ind',
            field=models.TextField(blank=True, default='Potong, laminating, jilid, dan finishing — satu distributor tepercaya untuk seluruh kebutuhan mesin percetakan dan photocopy Anda.', null=True, verbose_name='Beranda: paragraf pembuka'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, default='Distributor mesin percetakan & finishing', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_ind',
            field=models.CharField(blank=True, default='Distributor mesin percetakan & finishing', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_body',
            field=models.TextField(blank=True, default='Lexia Machinery, di bawah Pelita Graphic Supplies, menyediakan mesin potong kertas, laminating, jilid lem, dan mesin finishing lainnya untuk pelaku usaha percetakan dan photocopy di seluruh Indonesia.\n\nKini kami berkembang melayani Medan, Jakarta, dan seluruh Indonesia — dengan konsultasi langsung, dukungan purna jual, dan pengiriman ke seluruh penjuru negeri.', help_text='Satu baris kosong = paragraf baru.', verbose_name='Tentang: isi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_headline',
            field=models.CharField(blank=True, default='Distributor mesin percetakan tepercaya, sejak awal berdiri di Medan', max_length=200, verbose_name='Tentang: judul (H1)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Showroom / gudang. Rasio 4:3, mis. 1200x900.', null=True, upload_to='seo/', verbose_name='Tentang: foto'),
        ),
    ]
